export const LOCALIZATION = {
  EN: {
    APP_NAME: "In-flight Companion",
    LANGUAGES: "Languages",
    CHOOSE_LANGUAGE_ALERT: "Please select your language",
    WELCOME_ABOARD: "Welcome Aboard",
    TIME_TO_DESTINATION: "Time to Destiantion",
    ESTIMATED_ARRIVAL_TIME: "Estimated Arrival Time",
    SINGAPORE: "Singapore",
    SINGAPORE_CHANGI_AIRPORT: "Singapore Changi Airport",
    SHANGHAI: "Shanghai",
    SHANGHAI_PUDONG_INTL_AIRPORT: "Shanghai Pudong Intl Airport",
    LOCAL_TIME: "Local Time",
    INFLIGHT_SERVICES: "In-flight Services",
    DINING: "Dining",
    KRIS_WORLD: "KrisWorld",
    KRIS_SHOP: "KrisShop",
    SEAT_UPGRADE: "Seat Upgrade",
    OTHER_SERVICES: "Other Services",
    FEEDBACK: "Feedback"
  },
  ZH: {
    APP_NAME: "空中伴侣",
    LANGUAGES: "语言",
    CHOOSE_LANGUAGE_ALERT: "请选择您的语言",
    WELCOME_ABOARD: "欢迎登机",
    TIME_TO_DESTINATION: "飞行时间",
    ESTIMATED_ARRIVAL_TIME: "预计到达时间",
    SINGAPORE: "新加坡",
    SINGAPORE_CHANGI_AIRPORT: "新加坡樟宜机场",
    SHANGHAI: "上海",
    SHANGHAI_PUDONG_INTL_AIRPORT: "上海浦东国际机场",
    LOCAL_TIME: "当地时间",
    INFLIGHT_SERVICES: "机上服务",
    DINING: "用餐",
    KRIS_WORLD: "KrisWorld",
    KRIS_SHOP: "KrisShop",
    SEAT_UPGRADE: "升舱",
    OTHER_SERVICES: "其他服务",
    FEEDBACK: "反馈"
  }
};
