export type LanguageType = "EN" | "ZH_CN";

export const LOCALIZATION = {
  EN: {
    APP_NAME: "In-flight Companion",
    LANGUAGES: "Languages",
    CHOOSE_LANGUAGE_ALERT: "Please choose your language",
    CANCEL: "Cancel",
    WELCOME_ABOARD: "Welcome Aboard",
    TIME_TO_DESTINATION: "Time to Destination",
    ESTIMATED_ARRIVAL_TIME: "Estimated Arrival Time",
    SINGAPORE: "Singapore",
    SINGAPORE_CHANGI_AIRPORT: "Singapore Changi Airport",
    SHANGHAI: "Shanghai",
    SHANGHAI_PUDONG_INTL_AIRPORT: "Shanghai Pudong Intl Airport",
    LOCAL_TIME: "Local Time",
    INFLIGHT_SERVICES: "In-flight Services",
    DINING: "Dining",
    BEVERAGES: "Beverages",
    KRIS_WORLD: "KrisWorld",
    KRIS_SHOP: "KrisShop",
    SEAT_UPGRADE: "Seat Upgrade",
    CABIN_SERVICE: "Cabin Service",
    FEEDBACK: "Feedback",
    CHICKEN_RICE: "Chicken Rice",
    BEEF_NOODLES: "Beef Noodles",
    CHICKEN_RICE_DESCRIPTION: "Chick rice is some kind of rice",
    BEEF_NOODLES_DESCRIPTION: "Beef noodles is some kind of noodles",
    SET_A: "Set A",
    SET_B: "Set B",
    VEGETABLE_SALAD: "Vegetable Salad",
    VEGETABLE_SALAD_DESCRIPTION: "Vegetable Salad is some kind of salad",
    HEALTHY_CHOICE: "Healthy Choice",
    MAIN_COURSE: "Main Course",
    VEGETABLE: "Vegetable"
  },
  ZH_CN: {
    APP_NAME: "空中伴侣",
    LANGUAGES: "语言",
    CHOOSE_LANGUAGE_ALERT: "请选择您的语言",
    CANCEL: "取消",
    WELCOME_ABOARD: "欢迎登机",
    TIME_TO_DESTINATION: "剩余飞行时间",
    ESTIMATED_ARRIVAL_TIME: "预计到达时间",
    SINGAPORE: "新加坡",
    SINGAPORE_CHANGI_AIRPORT: "新加坡樟宜机场",
    SHANGHAI: "上海",
    SHANGHAI_PUDONG_INTL_AIRPORT: "上海浦东国际机场",
    LOCAL_TIME: "当地时间",
    INFLIGHT_SERVICES: "机上服务",
    DINING: "用餐",
    BEVERAGES: "饮品",
    KRIS_WORLD: "KrisWorld",
    KRIS_SHOP: "KrisShop",
    SEAT_UPGRADE: "办理升舱",
    CABIN_SERVICE: "客舱服务",
    FEEDBACK: "反馈",
    CHICKEN_RICE: "鸡肉饭",
    BEEF_NOODLES: "牛肉面",
    CHICKEN_RICE_DESCRIPTION: "鸡肉饭是饭",
    BEEF_NOODLES_DESCRIPTION: "牛肉面是面",
    SET_A: "套餐A",
    SET_B: "套餐B",
    VEGETABLE_SALAD: "蔬菜沙拉",
    VEGETABLE_SALAD_DESCRIPTION: "蔬菜沙拉是沙拉",
    HEALTHY_CHOICE: "健康选择",
    MAIN_COURSE: "主菜",
    VEGETABLE: "蔬菜"
  }
};
